spring:
  application:
    name: MonsterChess

  datasource:
    url: jdbc:postgresql://localhost:5436/monsterchess
    driver-class-name: org.postgresql.Driver
    username: monster
    password: chess
  flyway:
    enabled: true
    locations: classpath:db.migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080