CREATE TABLE movies
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tmdb_id          INTEGER,
    title            VARCHAR(255),
    release_year     INTEGER,
    is_deleted       BOOLEAN,
    add_to_watchlist BOOLEAN,
    is_ignored       BOOLEAN,
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE spoilers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tmdb_id      BIGINT                                  NOT NULL,
    spoiler_text TEXT,
    spoiler_type VARCHAR(255),
    is_verified  BOOLEAN,
    submitted_by VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    is_deleted   BOOLEAN,
    CONSTRAINT pk_spoilers PRIMARY KEY (id)
);

ALTER TABLE spoilers
    ADD CONSTRAINT FK_SPOILERS_ON_TMDB FOREIGN KEY (tmdb_id) REFERENCES movies (id);