version: "3.8"
services:
  postgres-db:
    container_name: bucketlist
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: bucket
      POSTGRES_PASSWORD: doggyhorse
      POSTGRES_DB: bucketlist
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5438:5432"

volumes:
  postgresql_data:
    driver: local