CREATE TABLE monster_type
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(255),
    special_ability VARCHAR(255),
    CONSTRAINT pk_monster_type PRIMARY KEY (id)
);

CREATE TABLE monsters
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    is_king         BOOLEAN,
    player_owner    INTEGER                                 NOT NULL,
    position_row    INTEGER,
    position_col    INTEGER,
    is_captured     BOOLEAN,
    monster_type_id BIGINT,
    CONSTRAINT pk_monsters PRIMARY KEY (id)
);

ALTER TABLE monster_type
    ADD CONSTRAINT uc_monster_type_name UNIQUE (name);

ALTER TABLE monsters
    ADD CONSTRAINT FK_MONSTERS_ON_MONSTER_TYPE FOREIGN KEY (monster_type_id) REFERENCES monster_type (id);