spring:
  application:
    name: SpoiledRotten

  datasource:
    url: jdbc:postgresql://localhost:5436/spoiled_rotten
    driver-class-name: org.postgresql.Driver
    username: spoiled
    password: rotten
  flyway:
    enabled: true
    locations: classpath:db.migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080
tmdb:
  api:
    key: 4de3f13a4cdd05831b95a97d3b3e2da6
